USE [master]
GO

/****** Object:  Database [Skkyl]    Script Date: 14/10/2018 18:14:04 ******/
CREATE DATABASE [Skkyl]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Skkyl', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Skkyl.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Skkyl_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Skkyl_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Skkyl] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Skkyl].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Skkyl] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Skkyl] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Skkyl] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Skkyl] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Skkyl] SET ARITHABORT OFF 
GO

ALTER DATABASE [Skkyl] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Skkyl] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Skkyl] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Skkyl] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Skkyl] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Skkyl] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Skkyl] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Skkyl] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Skkyl] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Skkyl] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Skkyl] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Skkyl] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Skkyl] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Skkyl] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Skkyl] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Skkyl] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Skkyl] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Skkyl] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Skkyl] SET  MULTI_USER 
GO

ALTER DATABASE [Skkyl] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Skkyl] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Skkyl] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Skkyl] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Skkyl] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Skkyl] SET QUERY_STORE = OFF
GO

USE [Skkyl]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Skkyl] SET  READ_WRITE 
GO

